FROM lballabio/boost:1.72.0-bionic

# Add and configure required tools

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y python python-pip unzip \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

FROM ubuntu:latest AS base
#
# Now install the needed packages.
RUN apt-get -y update && apt-get install -y default-jdk python3 python3-dev python3-pip net-tools wget dnsutils iputils-ping iputils-tracepath iputils-arping iputils-clockdiff unzip libboost-all-dev
RUN python3 -m pip install --upgrade pip 

# Note, I have added several other packages that provide networking utilities like
# ping, nslookup, ifconfig etc.


RUN python3 -m pip install jupyter ipywidgets jupyter_dashboards pythreejs bqplot matplotlib scipy

RUN jupyter dashboards quick-setup --sys-prefix
RUN jupyter nbextension enable --py --sys-prefix widgetsnbextension

from base AS dependencies

# Download and uncompress ORE

ARG ore_short_version=1.8.5
ARG ore_version=1.8.5.0
ARG ore_archive=ORE-${ore_short_version}.zip
ARG ore_folder=ORE-${ore_short_version}

ENV ore_version ${ore_version}

RUN wget https://github.com/OpenSourceRisk/Engine/releases/download/v${ore_version}/${ore_archive} \
&&  /usr/bin/unzip ${ore_archive} \
&& rm ${ore_archive}

# Whatever we do next, we do in the ORE folder

WORKDIR ${ore_folder}


# Add QuantLib

ARG quantlib_version=1.21
ENV quantlib_version ${quantlib_version}

RUN wget https://github.com/lballabio/QuantLib/releases/download/QuantLib-v${quantlib_version}/QuantLib-${quantlib_version}.tar.gz \
&& tar xfz ./QuantLib-${quantlib_version}.tar.gz \
&& rm QuantLib-${quantlib_version}.tar.gz \
&& mv QuantLib-${quantlib_version} QuantLib

From dependecies AS downloads

# Compile, as per instructions in the ORE user guide


RUN cd QuantLib \
    && ./configure \
    && make -j26

From downloads AS QuantLib

RUN cd QuantExt \
    && ./configure \
    && make -j26 \
    && ./test/quantext-test-suite

From QuantLib as QuantExt


RUN cd OREData \
    && ./configure \
    && make -j26 \
    && ./test/ored-test-suite

From QuantExt AS OREData

RUN cd OREAnalytics \
    && ./configure \
    && make -j26 \
    && ./test/orea-test-suite

From OREData as OREAnalytics


RUN cd App \
    && ./configure \
    && make -j26

ENV LC_NUMERIC C
